---
# The order of the roles is important as Ansible when the flag --tags
# is used will execute the roles in the order they are appear here
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300
      tags: [dependencies]
- hosts: all
  become: true
  roles:
    - role: startcloud_dependencies
      tags: [dependencies]
    - role: startcloud_service_user
      tags: [service_user]
    - role: startcloud_sdkman_install
      tags: [sdkman_install]
    - role: startcloud_sdkman_java
      tags: [sdkman_java]
    - role: startcloud_ssl
      tags: [startcloud_ssl]
    - role: startcloud_haproxy
      tags: [haproxy]
    - role: startcloud_mariadb
      tags: [mariadb]
    - role: startcloud_sdkman_gradle
      tags: [sdkman_gradle]
    - role: startcloud_sdkman_maven
      tags: [sdkman_maven]
    - role: startcloud_tomcat
      tags: [tomcat]
