---
-
  name: "Setting up Debian Installations"
  when: "ansible_os_family == 'Debian'"
  block:
    -
      name: "Gathering DEB architecture"
      ansible.builtin.shell: dpkg --print-architecture
      register: deb_architecture
    -
      name: "Log playbook progress"
      ansible.builtin.debug:
        msg:
          - "{{ progress_checks.dependencies.a.msg }}"
          - "{{ progress_checks.dependencies.a.val }}"
    -
      name: "Printing DEB architecture"
      ansible.builtin.debug:
        msg: "deb_architecture.stdout: {{ deb_architecture.stdout }}"
    -
      name: "Ensuring apt cache is updated"
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: true
    -
      name: "Log playbook progress"
      ansible.builtin.debug:
        msg:
          - "{{ progress_checks.dependencies.b.msg }}"
          - "{{ progress_checks.dependencies.b.val }}"
    -
      name: "Upgrading all apt packages"
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
    -
      name: "Adding Additional Dependencies {{ packages }}"
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
    -
      name: "Log playbook progress"
      ansible.builtin.debug:
        msg:
          - "{{ progress_checks.dependencies.c.msg }}"
          - "{{ progress_checks.dependencies.c.val }}"
