---
run_tasks: true
packages:
  - htop
  - lynx
  - lshw
  - libxml2-utils
  - tree
  - python3-pexpect
  - python3-pymongo
  - python3-pymysql
  - psutils
  - python3-psutil
  - libxml2-utils
  - acl
progress_checks:
  dependencies:
    a: { msg: '', val: 33 }
    b: { msg: '', val: 66 }
    c: { msg: '', val: 100 }
